### ISSUE TITLE
Cannot parse YAML file

### ISSUE THREAD

**Issue by grantmcdermott** [lettier/gifcurry#37]
I'm trying to run the CLI version of Gifcurry and keep running into the following error: `[WARNING] Could not parse the /PATH/TO/text-overlays.yaml YAML file!`

Here is the file in question:
```
- text: This is a test.
      fontFamily:   Sans
      fontStyle:    30
      fontStretch:  Normal
      fontWeight:   Normal
      fontSize:     800
      origin:       NorthWest
      xTranslation: 0.0
      yTranslation: 0.0
      rotation:     0
      startTime:    1.000
      durationTime: 8.000
      outlineSize:  10
      outlineColor: rgb(1,100,10)
      fillColor:    rgb(255,255,0)
```
Are there any obvious errors that jump out at you?

(FWIW, I think that including an example YAML file in the docs would be really helpful.)

Thanks for a cool package!

**Comment by lettier** [comment]
Hello @grantmcdermott ,

I apologize for the lack of examples.  I'll add some and update the help output for the upcoming release.

Here is the corrected version.

```yaml
- text: This is a test.
  fontFamily:   Sans
  fontStyle:    Normal
  fontStretch:  Normal
  fontWeight:   30
  fontSize:     800
  origin:       NorthWest
  xTranslation: 0.0
  yTranslation: 0.0
  rotation:     0
  startTime:    1.000
  durationTime: 8.000
  outlineSize:  10
  outlineColor: rgb(1,100,10)
  fillColor:    rgb(255,255,0)
```

Here is the difference (`{-removed-}` and `{+added+}`).

![Screenshot_2019-03-16_21-52-53](https://user-images.githubusercontent.com/1661343/54482086-5e4a8a80-4814-11e9-8a50-f7136026985c.png)

- Only one indent under `- text: This is a test.`.
- `fontStyle` must be a string such as `Normal`, `Bold`, or `Oblique`.
- `fontWeight` must be an integer.

:+1:
